### ISSUE TITLE
What is the output format

### ISSUE THREAD

**Issue by spth** [rovaniemi/osm-graph-parser#7]
osm-graph-parser outputs _some_ json graph representation.

Is this compatible with any of the many more-or-less established existing standards for encoding graphs in json? If not, would it make sense to use such a more-widely use format?

Philipp

P.S.: Probably the most widely known is http://jsongraphformat.info/, which also has links to 4 other formats ("Similar Projects") on their start page. A 6th would be the Netflix one: http://netflix.github.io/falcor/documentation/jsongraph.html

**Comment by rovaniemi** [comment]
osm-graph-parser currently offers the graph represented as an adjacency list (as seen in Cormen's Introduction to Algorithms 3rd ed. p.589). We use this format because it suited our specific needs. We want to be able to use the output graph (for example, run Dijkstra's algorithm on it) directly without having to parse a generalized standard format.

Another reason is that the current format is pretty compact. If we were to use the [jsongraphformat](https://github.com/jsongraph/json-graph-specification), the output file size would increase significantly.

For example, here's an example graph:

![Imgur](http://i.imgur.com/whHd4gV.png)

Our output will look like this:
```json
[
  {
    "la": 10.0000000,
    "lo": 10.0000000,
    "e": [
      {
        "i": 2,
        "w": 200
      },
      {
        "i": 1,
        "w": 100
      }
    ]
  },
  {
    "la": 11.1111111,
    "lo": 11.1111111,
    "e": [
      {
        "i": 3,
        "w": 100
      }
    ]
  },
  {
    "la": 12.2222222,
    "lo": 12.2222222,
    "e": [
      {
        "i": 0,
        "w": 200
      },
      {
        "i": 1,
        "w": 300
      },
      {
        "i": 3,
        "w": 400
      }
    ]
  },
  {
    "la": 13.3333333,
    "lo": 13.3333333,
    "e": [
      {
        "i": 1,
        "w": 100
      }
    ]
  }
]
```

Jsongraphformat would look like this.
```json
{
    "g": {
        "n": [
            {
                "id": "0",
                "la": 10.0000000,
                "lo": 10.0000000
            },
            {
                "id": "1",
                "la": 11.1111111,
                "lo": 11.1111111
            },
            {
                "id": "2",
                "la": 12.2222222,
                "lo": 12.2222222
            },
            {
                "id": "3",
                "la": 13.3333333,
                "lo": 13.3333333
            }
        ],
        "e": [
            {
                "s": "1",
                "t": "2",
                "w": "100"
            },{
                "s": "1",
                "t": "3",
                "w": "200"
            },{
                "s": "2",
                "t": "4",
                "w": "100"
            },{
                "s": "3",
                "t": "1",
                "w": "200"
            },{
                "s": "3",
                "t": "2",
                "w": "300"
            },{
                "s": "3",
                "t": "4",
                "w": "400"
            },{
                "s": "2",
                "t": "4",
                "w": "100"
            }
        ]
    }
}
```
Our representation has 273 characters without whitespace. Jsongraphformat has 387 characters without whitespace. So our format is approximately two thirds the size of jsongraphformat.

Do you have a use case in mind for which a generalized standard JSON graph format would be better suited?
